- name: Run prerequisite checks for patching a system
  hosts: all
  gather_facts: yes
  vars:
    memory_free_required: 1000
  tasks:
    - name: Check memory utilization
      assert:
        that:
          - ansible_memory_mb.real.free > memory_free_required
        msg: "System has less than {{ memory_free_required }} MB of free memory: {{ ansible_memory_mb.real.free }}"

    - name: "Ensure that free space on {{ mountname }} is greater than 20%"
      assert:
        that:
          - item.size_available > item.size_total|float * 0.2
        msg: "Disk space has reached 80% threshold"
      when: item.mount == "/"
      with_items: "{{ ansible_mounts }}"
